project/routes/blog/views.py
# /routes/blog/views.py

### Imports ###
import sys
sys.path.insert(0, '/vagrant/leandras_site/project/model/')
from model import Base, Blog
from connect import connect
from flask import render_template, Blueprint, request, redirect, url_for, session, make_response, flash
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import func, desc
from sqlalchemy.orm import sessionmaker
from datetime import datetime
import json

### Config ###
blog_blueprint = Blueprint('blog', __name__, template_folder='templates')

### Database connection ###
def dbconnect():
	# Connect to the database
	con = connect()
	Base.metadata.bind = con
	# Creates a session
	DBSession = sessionmaker(bind=con)
	dbsession = DBSession()
	return dbsession

### routes ###
@blog_blueprint.route('/blog/<cat>')
def blog(cat):
	dbsession = dbconnect()
	if cat in {'all','general','crafting','baking','travel'}:
		if cat == 'all':
			posts = dbsession.query(Blog).filter_by(hidden=False, updated=True).order_by(Blog.bid.desc()).all()
		else:
			posts = dbsession.query(Blog).filter_by(hidden=False, updated=True, category=cat).order_by(Blog.bid.desc()).all()
		return render_template('blog.html', posts=posts)
	else:
		return render_template('404.html')

@blog_blueprint.route('/blog/<int:bid>')
def blog_post(bid):
	dbsession = dbconnect()
	post = dbsession.query(Blog).filter_by(bid=bid).order_by(Blog.pid.desc()).first()
	return render_template('blog_post.html', post=post)

@blog_blueprint.route('/blog/newest')
def blog_new():
	dbsession = dbconnect()
	post = dbsession.query(Blog).order_by(Blog.pid.desc()).first()
	return	render_template('blog_post.html', post=post)

@blog_blueprint.route('/blog/admin')
def blog_admin():
	dbsession = dbconnect()
	posts = dbsession.query(Blog).filter_by(updated=True).order_by(Blog.bid.desc()).all()
	return render_template('blog_admin.html', posts=posts)

@blog_blueprint.route('/blog/admin/add')
def blog_admin_add():
	return render_template('blog_admin_add.html')

@blog_blueprint.route('/blog/admin/edit/<int:id>')
def blog_admin_edit(id):
	dbsession = dbconnect()
	post = dbsession.query(Blog).filter_by(bid=id).order_by(Blog.pid.desc()).first()
	return render_template('blog_admin_edit.html', post=post)

@blog_blueprint.route('/blog/admin/alter/<action>/<int:id>', methods = ['POST'])
def blog_admin_alter(action,id):
	dbsession = dbconnect()
	if action == 'delete':
		post = dbsession.query(Blog).filter_by(bid = id).order_by(Blog.pid.desc()).first()
		post.hidden = True
		dbsession.commit()
		flash("Blog post #%s had been deleted." % id)
		return redirect(url_for('blog.blog_admin'))
	if action == 'undelete':
		post = dbsession.query(Blog).filter_by(bid = id).order_by(Blog.pid.desc()).first()
		post.hidden = False
		dbsession.commit()
		flash("Blog post #%s had been restored." % id)
		return redirect(url_for('blog.blog_admin'))
	if action == 'add':
		old_id = dbsession.query(Blog.bid).order_by(Blog.bid.desc()).first()
		new_id = old_id[0]+1
		title = request.form['title']
		sub_title = request.form['sub_title']
		author = 'Leandra Clifton'
		date_time = datetime.now()
		category = request.form['category']
		content = request.form['content']
		
		post = Blog(bid = new_id,
					title = title,
					sub_title = sub_title,
					author = author,
					date_time = date_time,
					category = category,
					content = content,
					hidden = False,
					updated = True)
		dbsession.add(post)
		dbsession.commit()
		flash("Blog post has been added.")
		return json.dumps({'success':True}), 200, {'ContentType':'application/json'} 
	if action == 'edit':
		o_post = dbsession.query(Blog).filter_by(bid = id).order_by(Blog.pid.desc()).first()
		o_post.updated = False
		dbsession.commit()

		title = request.form['title']
		sub_title = request.form['sub_title']
		author = 'Leandra Clifton'
		date_time = datetime.now()
		category = request.form['category']
		content = request.form['content']
		
		post = Blog(bid = id,
					title = title,
					sub_title = sub_title,
					author = author,
					date_time = date_time,
					category = category,
					content = content,
					hidden = False,
					updated = True)
		dbsession.add(post)
		dbsession.commit()
		flash("Blog post #%s has been edited." % id)
		return json.dumps({'success':True}), 200, {'ContentType':'application/json'} 

project/routes/blog/templates/blog.html
{% extends 'base.html' %}
{% block content %}

  <!-- Page Header -->
    <header class="masthead" style="background-image: url('{{ url_for('static', filename='img/home-bg.jpg') }}')">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Leandra's Blog</h1>
              <span class="subheading">A Blog Theme by Start Bootstrap</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
        {% for post in posts %}
          <div class="post-preview">
            <a href="{{ url_for('blog.blog_post', bid=post.bid) }}">
              <h2 class="post-title">
                {{ post.title }}
              </h2>
              <h3 class="post-subtitle">
                {{ post.sub_title }}
              </h3>
            </a>
            <p class="post-meta">Posted by {{ post.author }} on {{ post.date_time.strftime('%B %d, %Y') }}</p>
          </div>
          {% endfor %}
          <hr>
        </div>
      </div>
    </div>
{% endblock %}

project/routes/blog/templates/blog_admin.html
{% extends 'base.html' %}
{% block content %}
  <main role="main" class="container">
    <div class="jumbotron">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <hr>
          <div class="flashes flash_msg">
          {% for message in messages %}
            {{ message }}
          {% endfor %}
          </div>
          <hr>
        {% endif %}
      {% endwith %}

      <div class="row">
        <div class="col-md">
          <h1>Blog Admin</h1>
        </div>
        <div class="col-md">
          <a href="/blog/admin/add"><button class="btn btn-primary">New Post</button></a>
        </div>
      </div>

      <p class="lead">Leandra's Blog Admin Page</p>
      <table id = "incidents" class="table table-striped">
          <thead>
            <tr>
              <th>ID #</th>
              <th>Title</th>
              <th>Author</th>
              <th>Date</th>
              <th>Time</th>
              <th>Category</th>
              <th>Edit</th>
              <th>Delete</th>
            </tr>
          </thead>
          <tbody>
          {% for post in posts %}
            <tr>
              <th>{{post.bid}}</th>
              <th><a href="{{ url_for('blog.blog_post', bid=post.bid) }}">{{post.title}}</a></th>
              <th>{{post.author}}</th>
              <th>{{post.date_time.strftime('%B %d, %Y')}}</th>
              <th>{{post.date_time.strftime('%H:%M')}}</th>
              <th>{{post.category}}</th>
              <th>
                <a href="{{ url_for('blog.blog_admin_edit', id=post.bid) }}">
                  <button type="button" class="btn btn-info btn-lg editBtn">Edit</button></th>
                </a>
              </th>
              {% if post.hidden==False %}
                <th><button type="button" class="btn btn-info btn-lg deleteBtn" data-toggle="modal" data-target="#myModal" id="{{post.bid}}">Del</button></th>
              {% else %}
                <th><button type="button" class="btn btn-info btn-lg unDeleteBtn" data-toggle="modal" data-target="#myModal" id="{{post.bid}}">UnD</button></th>
              {% endif %}
            </tr>
          {% endfor %}
          </tbody>
        </table>
    </div>
    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Delete Blog Post</h4>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete this blog post?</p>
            <form id="deleteFrm" action="" method="post">
              <input class="submit" type='submit' value='Yes'>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>

      </div>
    </div>
  </main>
{% endblock %}

project/routes/blog/templates/blog_admin_add.html
{% extends 'base.html' %}
{% block content %}
  <main role="main" class="container">
    <div class="jumbotron">

      <h1>Blog Admin Add</h1>
      <p class="lead">Add a new blog page</p>
      <form>
          <h3>Title:</h3>
          <input type="text" name="title">
          <br>
          <br>
          <h3>Subtitle:</h3>
          <input type="text" name="sub_title">
          <br>
          <br>
          <h3>Category:</h3>
          <input type ='radio'  name='category' value ='general'> General
          <br>
          <input type ='radio'  name='category' value ='crafting'> Crafting
          <br>
          <input type ='radio'  name='category' value ='baking'> Baking/Cooking
          <br>
          <input type ='radio'  name='category' value ='travel'> Travel
          <br>
          <br>
          <h3>Content:</h3>
          <input type="hidden" name="contents">
          <!-- Create the editor container -->
          <div id="addEditor">
          </div>

          <br>
          <div class="row">
            <button class="btn btn-primary" type="submit">Save Profile</button>
          </div>
      </form>

    </div>
  </main>
{% endblock %}

project/routes/blog/templates/blog_admin_del.html
{% extends 'base.html' %}
{% block content %}
  <main role="main" class="container">
    <div class="jumbotron">
      <h1>Blog Admin Delete</h1>
      <p class="lead">Delete a blog page</p>
    </div>
  </main>
{% endblock %}

project/routes/blog/templates/blog_admin_edit.html
{% extends 'base.html' %}
{% block content %}
  <main role="main" class="container">
    <div class="jumbotron">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <hr>
          <div class="flashes flash_msg">
          {% for message in messages %}
            {{ message }}
          {% endfor %}
          </div>
          <hr>
        {% endif %}
      {% endwith %}
      <h1>Edit Blog Post #{{post.bid}}</h1>
      <p class="lead">Spruce it up just a bit...</p>
      <form>
        <label><strong>Title:</strong></label>
        <br>
        <input type="text" name="title" value="{{post.title}}">
        <br>
        <br>
        <label><strong>Subitle:</strong></label>
        <br>
        <input type="text" name="sub_title" value="{{post.sub_title}}">
        <br>
        <br>
        <label><strong>Category:</strong></label>
        <br>
        <input type ='radio'  name='category' value ='general' {% if post.category == 'general' %}checked='checked'{% endif %}> General
        <br>
        <input type ='radio'  name='category' value ='crafting' {% if post.category == 'crafting' %}checked='checked'{% endif %}> Crafting
        <br>
        <input type ='radio'  name='category' value ='baking' {% if post.category == 'baking' %}checked='checked'{% endif %}> Baking/Cooking
        <br>
        <input type ='radio'  name='category' value ='travel' {% if post.category == 'travel' %}checked='checked'{% endif %}> Travel
        <br>
        <br>
        <label><strong>Content:</strong></label>
        <br>
        <input type="hidden" name="content">
        <!-- Create the editor container -->
        <div id="addEditor">
        </div>
        <!--
        <br>
        <input type='submit' value='Submit'>
        -->
        <br>
        <div class="row">
          <button class="btn btn-primary" type="submit">Submit</button>
        </div>
      </form>
    </div>
  </main>
  <script>
    $('#addEditor').append({{post.content | safe}});
    var postType = 'edit';
    var post_id = {{post.bid}};
  </script>
{% endblock %}

project/routes/blog/templates/blog_post.html
{% extends 'base.html' %}
{% block content %}
  <!-- Page Header -->
    <header class="masthead" style="background-image: url('{{ url_for('static', filename='img/post-bg.jpg') }}')">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1>{{ post.title }}</h1>
              <h2 class="subheading">{{ post.sub_title }}</h2>
              <span class="meta">Posted by
                {{ post.author }}
                on {{ post.date_time.strftime('%B %d, %Y') }}</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->
    <article>
      <div class="container">
        <div class="row">
          <div id="blog_post_content" class="col-lg-8 col-md-10 mx-auto">
          </div>
        </div>
      </div>
    </article>
    <script>
      var blog_post_content = document.getElementById("blog_post_content");
      if(blog_post_content){
        $('#blog_post_content').html({{ post.content|safe }});
      }
    </script>
{% endblock %}